### ISSUE TITLE
High CPU usage when scroll

### ISSUE THREAD

**Issue by Innei** [wellle/context.vim#68] opened 2020-03-28 03:41 UTC
Very cool idea. But there are some performance problems. When I continuous scrolling, the `nvim` process take up high CPU usage.
![image](https://user-images.githubusercontent.com/41265413/77814098-feeeae00-70e8-11ea-8b56-47348dca3a64.png)

**Comment by LinArcX** [comment] 2020-03-28 07:46
Same issue!

**Comment by maxigit** [comment] 2020-04-16 08:19
Maybe a solution, would be to disable auto commands and instead display the context on `CustorHold` instead.

**Comment by zsugabubus** [comment] 2020-05-03 23:08
###### I used “context/autoload.vim” as test file + copied its contents two or three times to get a longer corpus.

NeoVim. When I press <kbd>j</kbd>, but especially <kbd>k</kbd>, I measure a solid 100% usage and the whole screen flickers in urxvt. In alacritty it’s worse by 10-15% but at least barely flickers. Cursor often lags/jumps during scrolling. When I release `j` the cursor still keeps going for a little bit until it finally stops. 

This lagginess is even more noticeable when `vim-signify` is active.

Compared to [m](https://github.com/zsugabubus/vim-paperplane)y clone, it “only” consumes 70% CPU (and a bit less in alacritty) and I absolutely don’t feel laggy.

The first thing that came into my mind, is you could try using `noautocmd`. For example, I prefixed my [update call](https://github.com/zsugabubus/vim-paperplane/blob/75d73949f3c613c10be7d56c59f0022966a2beca/plugin/paperplane.vim#L30) with it, so autocmds will not slow the update process down. It won’t make magic, but surely will help a bit with `vim-signify` + auto completers.

**Comment by wellle** [comment] 2020-07-12 21:57
Hey thanks everyone! I did some profiling to see if anything comes up. What I found on my machine was that it was dominated by `context#popup#nvim#redraw_screen()`, which is because we call `:redraw` and `:mode`. (see https://github.com/wellle/context.vim/issues/23)

So if you see high CPU usage, could you please try adding this to your vimrc and tell me if that improves the situation for you?
```vim
let g:context_nvim_no_redraw = 1
```

If it doesn't, could I ask you to do some profiling for me so I can see what's being slow for you?
Open a file where you see high CPU usage and run these commands:
```vim
:profile start context.log
:profile file *
:profile func *
```
Then quit vim and share the `context.log` file with me in this issue. Thank you!

**Comment by wellle** [comment] 2020-07-13 20:11
Additionally/alternatively, if you see high CPU usage, could you please try this branch and see if that reduces the CPU usage? Thanks!
https://github.com/wellle/context.vim/tree/68-temp

(This branch uses fake context lines to avoid actually calculating the context. I'm hoping to see from this if the calculation of the context is the actual bottleneck here.)

**Comment by Procrat** [comment] 2020-10-27 16:18
Thanks for the hard work on this, @wellle!

I'm hitting some sluggish behaviour when scrolling as well. I already had `let g:context_nvim_no_redraw = 1` set (which was definitely necessary). I just tried out the `68-temp` like you suggested and it does make this better! This is a profile of a single scroll through an HTML file with a fair amount of nested indentation on that branch: [before.log](https://github.com/wellle/context.vim/files/5446423/before.log) and [after.log](https://github.com/wellle/context.vim/files/5446422/after.log). This is great!

Despite that clear win, I have to say I'm a bit suspicious of that profiling output: I also noticed some sluggish behaviour on a markdown file with a decent amount of nesting and it doesn't seem quite fixed by switching to `68-temp`. Moreover, the profiling output didn't show anything out of the ordinary even though the difference couldn't be more obvious. With some trial and error, I found that if I turn off either `context.vim` or [`vim-journal`](https://github.com/junegunn/vim-journal), it works smoothly, but with both turned on, it doesn't. The profiling logs don't seem to show it: [context-and-journal.log](https://github.com/wellle/context.vim/files/5446549/context-and-journal.log), [only-context.log](https://github.com/wellle/context.vim/files/5446550/only-context.log), [only-journal.log](https://github.com/wellle/context.vim/files/5446552/only-journal.log), and [neither.log](https://github.com/wellle/context.vim/files/5446583/neither.log). (Unrelated, it's weird that when `context.vim` is loaded by itself, the calls seem to double? I reran it a couple of times and I didn't mess up the filenames.)

Let me know if I can be of any more help!

**Comment by wellle** [comment] 2020-10-27 16:28
Thank you for helping me out here! I will try to look into your files soon. Much appreciated! ❤️

**Comment by ericonr** [comment] 2020-10-29 05:27
> let g:context_nvim_no_redraw = 1

Thanks for this one, it seems to have completely fixed the issue on my side! Do you plan to keep it as a configuration option?

**Comment by wellle** [comment] 2020-10-29 23:00
@ericonr: Yes I will keep this setting until the Neovim bug neovim/neovim#11597 has been resolved.

@Procrat: Thanks again for the profiling output. I had a look at your `before.log` file and extracted this overview:
```java
1.35 context#update
    1.12 context#popup#update_context
        0.86 s:show()
            0.85 context#popup#redraw
                0.643 context#line#display // <-- TODO: cache this
                    0.265 synIDattr
                0.08 matchaddpos
                0.064 context#popup#nvim#redraw
                    0.04 execute wincmd w
        0.25 context#popup#get_context
            0.126 context#context#get
                0.06 s:get_context_line()
                    0.034 context#line#make_trimmed
                        0.01 s:trim()
                    0.013 g:context.Indent
                0.019 s:join
            0.09 context#util#filter
        0.063 s:show_cursor()
            0.05 execute normal
    0.12 context#util#update_state
        0.087 calculate sign_width
```
This is very helpful to me! The biggest quick win appears to be calls to `context#line#display()` which make up 47% of all execution time within context.vim. And this is all on cached context lines. I will look into caching the output of those calls, so this should already shave off almost half of the execution time.

Once that's done I might ask you again to rerun the comparison.

In the meantime I shall also rebase the `68-temp` branch on master. I noticed that the two versions aren't directly compatible anymore as we did major changes on `master` since I had created `68-temp`.

I had a quick look at the log files related to `vim-journal`. I have no idea what's going on there. We might look into that later.

**Comment by Procrat** [comment] 2020-10-31 01:37
Awesome! More than happy to do a rerun afterwards.

Perhaps a bit off-topic, but is there something I can do to debug the strange interaction with `vim-journal` or profile it in some other way? It really looks like the profiling output isn't capturing all that is happening. Would that be a Neovim bug? What would you do in my case?

**Comment by wellle** [comment] 2020-10-31 22:50
Sorry, I'm afraid I don't really have good advice for you about that. What I would do is probably disable parts of the plugins (similar to what I did in `68-temp`) until the behavior improves. And then try to go from there. I'm tempted to do that for you, but I'm afraid I won't find the time for that anytime soon. But just in case, maybe you can share a file where you observe the sluggishness?

**Comment by Procrat** [comment] 2020-11-07 22:13
I can reproduce it with [a small but deeply nested list](https://github.com/wellle/context.vim/files/5505524/test.txt) on [a minimal init.vim](https://github.com/wellle/context.vim/files/5505537/test-init.vim.txt) (uploaded as `.txt` because of GitHub restrictions). I'm running this on the latest Neovim (v0.5.0-818-gdf750e724) by the way.

Thanks for the advice. I might give that a go when I find some time.

**Comment by wellle** [comment] 2020-11-08 19:56
Thanks! I also managed to reproduce it now on a similar file with deep nesting. I wrote a basic benchmark script, see https://github.com/wellle/context.vim/compare/68-cache-display-lines

Btw, that branch also includes caching of the display lines, it seems to be an improvement. But I'm thinking of reconsidering the caching approach in a more drastic way, as apparently currently a lot of time is still being spent on collecting which lines are being part of the context.

**Comment by natdm** [comment] 2020-11-26 16:16
It looks like setting `no_redraw` fixes the issue but creates another? If scrolling up, you can actually scroll in to context instead of actually scrolling the file up.

**Comment by wellle** [comment] 2020-11-26 16:20
Yes, that's a display bug in neovim, see https://github.com/neovim/neovim/issues/11597. That's why we always do the expensive redraw by default.

**Comment by natdm** [comment] 2020-11-26 16:27
> Yes, that's a display bug in neovim, see [neovim/neovim#11597](https://github.com/neovim/neovim/issues/11597). That's why we always do the expensive redraw by default.

ahhhh, I understand it now. Thank you!

**Comment by wellle** [comment] 2020-12-30 21:08
Hey, I've been working on a different approach which allows for better caching, and it seems to have a good impact on performance as far as I can tell. I'd love if some of you could give it a shot and let me know if that improves the usability for you. Thanks in advance! 🙏 

Branch `68-incremental-cache` https://github.com/wellle/context.vim/compare/68-incremental-cache

**Comment by natdm** [comment] 2021-01-07 00:55
Will try it out and report back in a few days

**Comment by wellle** [comment] 2021-01-20 20:54
@natdm: Did you get a chance to try it out?

Don't worry if you didn't, I'd just merge it in that case, just want to check with you first in case you did :v:

**Comment by natdm** [comment] 2021-01-20 22:38
> @natdm: Did you get a chance to try it out?
> 
> Don't worry if you didn't, I'd just merge it in that case, just want to check with you first in case you did ✌️

Hey, sorry for the lack of response. I did have it on for a few days and the main thing I noticed was that it stops scrolling when it has to rerender. It stutters quite a bit then stops. Let me get a video if you'd like.

**Comment by natdm** [comment] 2021-01-20 22:44
https://youtu.be/EP1k7XUETM8

**Comment by wellle** [comment] 2022-05-01 19:20
I've removed the expensive call to `:mode` in https://github.com/wellle/context.vim/pull/115. Performance in Neovim should be improved now. Sorry for the big delay here. So I'm closing this. Thanks everybody! 🙌 

(Btw, I don't think I want to switch to the approach explored in the branch mentioned above. I believe it's good, but also somewhat experimental and I don't think I have the time currently to follow through if it breaks things I hadn't tested properly yet.)

**Closed by wellle** 2022-05-01 19:20 UTC
