### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by zoefiri** [wellle/context.vim#106] opened 2021-05-14 06:37 UTC
so I love this idea _but_ for some reason it's painfully slow, like, hold my down arrow for a couple seconds and then watch the editor finish scrolling for another few seconds kind of slow. Is something weird with my vimrc or is this how performance is supposed to be?

[init.vim.txt](https://github.com/wellle/context.vim/files/6477003/init.vim.txt)
there's my vimrc,  and here's my nvim --version output.

```nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.4.4/build/config -I/builddir/neovim-0.4.4/src -I/usr/include -I/builddir/neovim-0.4.4/build/src/nvim/auto -I/builddir/neovim-0.4.4/build/include
Compiled by void-buildslave@a-hel-fi

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info```

**Comment by polyzen** [comment] 2021-05-14 09:29
Seems to be a duplicate of #68.

**Closed** 2021-05-20 04:23 UTC
