### ISSUE TITLE
floating window, sometimes additionally rendered somewhere else?

### ISSUE THREAD

**Issue by syphar** [wellle/context.vim#36] opened 2020-02-01 15:21 UTC
First of all, really helpful plugin for bigger codebases / files and smaller screens. I really like it. 

But I often have the some old context rendered into the middle of the window. See screenshot. 

![image](https://user-images.githubusercontent.com/540890/73594517-6801dd00-450f-11ea-96fd-85690fd4fcbc.png)

It's somehow related to my FZF window, because it's in exactly the same position (I use a [custom method](https://github.com/syphar/dotfiles/blob/7843ce78bc1cc966e5b8e1664a30ce6acf39703e/.config/nvim/plugin_config.vim#L77-L98) to put fzf into a floating window. 

I'm definitely not good enough in vim/neovim to say it the problem is something with context here, or with my method.

**Comment by syphar** [comment] 2020-02-01 15:26
(if needed I'm happy to work out a minimal neovim-config to reproduce this)

**Comment by wellle** [comment] 2020-02-01 22:33
Thank you, I can reproduce the issue with your custom layout function. I'll look into this 👍

**Comment by syphar** [comment] 2020-02-02 06:49
thanks @wellle !  

funny story, I was just about to create this issue about random context appearing and my inability to reproduce it, then it came to me :) (rubber duck debugging I guess 😄 )

**Comment by wellle** [comment] 2020-02-02 22:17
FYI I started looking into it and feel like I understand now what's happening.
1. When the floating window gets opened there's a CursorMoved autocommand being fired. At that time the popup window appears to be the previous buffer which is unexpected. (I might open a neovim issue about that later). context.vim picks that up and generates a context and shows it in a popup window (which seems to be below the fzf popup). Once the fzf popup gets closed the context.vim popup is still being displayed.
2. I'll try to detect when a window is a floating window and disable contexts popups for such windows.
2. The check of when to update the layout (which includes closing context popups of closed windows) is flawed. We currently only check how many windows there are, but in this case the fzf popup closes shortly after the context.vim popup gets opened, so the number doesn't change between our checks. (Another way to trigger layout update is resizing the window. The extra floating window should disappear then) I'll look into improving that.

**Comment by syphar** [comment] 2020-02-03 03:53
thanks for the research :) interesting behaviour, you seem to pump into more than one neovim problem :) (https://github.com/wellle/context.vim/issues/23) 

As the vimscript-noob I am, I added `autocmd  FileType fzf ContextDisable`, which seems to work around it (no idea if there is a better way).

**Comment by nkakouros** [comment] 2020-02-06 13:28
In hope of adding useful information, I also have an issue with the floating window when resizing a window that has context showing. To reproduce split vertically, open a long file in one window and resize using the mouse. The context window does not resize.

**Comment by wellle** [comment] 2020-02-06 19:47
@nkakouros: Thank you for the feedback. I didn't manage to reproduce that. Could you give some details (which terminal, which Vim/Neovim version, maybe you can give example files and show some before and after screenshots). And to me it seems unrelated to this issue, could you open a separate one for your use case? Thanks!

**Comment by wellle** [comment] 2020-02-15 23:24
@syphar: FYI I did open a Neovim issue: https://github.com/neovim/neovim/issues/11878

**Closed** 2020-02-22 22:08 UTC
